apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goat-monitor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: goat.local # Replace with your resolveable DNS name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: goat-monitor
            port:
              number: 80